-- Задание №1
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_TEMP_FILES;

-- Задание №2
CREATE TABLESPACE PVG_QDATA
DATAFILE 'PVG_QDATA.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M
OFFLINE;

ALTER USER C##PVG QUOTA 2M ON PVG_QDATA;

ALTER TABLESPACE PVG_QDATA ONLINE;

CREATE TABLE PVG_T1
(
    Id number(6) primary key,
    Worker nvarchar2(20)
)TABLESPACE PVG_QDATA;

INSERT INTO PVG_T1 (Id, Worker) VALUES (1, 'Ваня');
INSERT INTO PVG_T1 (Id, Worker) VALUES (2, 'Никита');
INSERT INTO PVG_T1 (Id, Worker) VALUES (3, 'Никита');

select * from PVG_T1;

-- Задание №3
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'PVG_QDATA';

-- Задание №4
DROP TABLE PVG_T1;
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'PVG_QDATA';
SELECT * FROM USER_RECYCLEBIN;
COMMIT;

-- Задание №5
FLASHBACK TABLE PVG_T1 TO BEFORE DROP;
SELECT * FROM PVG_T1;

-- Задание №6
BEGIN
FOR k in 4..10000
    LOOP
    INSERT INTO PVG_T1 (Id) VALUES (k);
    end loop;
    COMMIT;
END;

-- Задание №7
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS, BUFFER_POOL FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'PVG_QDATA';
SELECT * FROM USER_EXTENTS WHERE TABLESPACE_NAME = 'PVG_QDATA';

-- Задание №8
DROP TABLESPACE PVG_QDATA INCLUDING CONTENTS AND DATAFILES;

-- Задание №9
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;

-- Задание №10
SELECT * FROM V$LOGFILE;

-- Задание №11/12

CREATE DATABASE ADD LOGFILE GROUP 4 'D:/бд/LABA4/redo04.log' SIZE 50m BLOCKSIZE 512;
CREATE DATABASE ADD LOGFILE MEMBER 'D:/бд/LABA4/redo04.log' TO GROUP 4;
CREATE DATABASE ADD LOGFILE MEMBER 'D:/бд/LABA4/redo04.log' TO GROUP 4;

SELECT * FROM V$LOG;

ALTER SYSTEM SWITCH LOGFILE;

-- Задание №13
ALTER DATABASE DROP LOGFILE GROUP 4;

-- Задание №14
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;

--Задание №15
SELECT MAX(SEQUENCE#) AS LAST_ARCHIVE_NUMBER
FROM V$ARCHIVED_LOG;

-- Задание №17
SELECT * FROM V$LOG;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 ='LOCATION=/opt/oracle/oradata/XE/Archive';
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;

-- Задание №19
SELECT * FROM V$CONTROLFILE;

-- Задане №20 (В консоли)
-- В консоли: SHOW PARAMETER CONTROL;

-- Задание №21 (В консоли)
-- В консоли: SHOW PARAMERER spfile;

-- Задание №22
CREATE PFILE = 'GKV_PFILE.ora' FROM SPFILE;

-- Задание №23
SELECT * FROM V$PWFILE_USERS;
-- В консоли: show parameter remote_login_passwordfile;

-- Задание №24
SELECT * FROM V$DIAG_INFO;

SELECT DISTINCT SEGMENT_TYPE FROM DBA_SEGMENTS;

--/opt/oracle/dbs/spfileXE.ora
